#!/usr/bin/env python3
"""
Emit cached OCR pages as Typst, behind a compile gate.

Nothing reaches the chapter file until the section compiles standalone. That
is the whole point of the rebuild: the previous pipeline wrote LaTeX-in-mitex
to disk and then spent 1080 lines converting it back. Here the conversion
happens at write time and a section that will not compile is never spliced in.

Sections are delimited in the chapter by marker comments, so re-emitting a
section replaces it in place instead of appending a duplicate. Anything
outside the markers — the symbol table, your hand edits to other sections —
is left untouched.

Usage
-----
    python pipeline/emit.py --chapter ch1 --section 2.1
    python pipeline/emit.py --chapter ch1 --all
    python pipeline/emit.py --chapter ch1 --section 2.1 --dry-run
"""

from __future__ import annotations

import argparse
import re
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import corrections as C
import mathconv
import sections as S
import symtab
from config import CHAPTER_PDFS
import ocrlib
from term import console

_HERE = Path(__file__).parent
CACHE_ROOT = _HERE / "cache"
CHAPTERS_DIR = _HERE.parent / "src" / "chapters"
PREAMBLE = _HERE.parent / "src" / "preamble.typ"
REPO_ROOT = _HERE.parent

BEGIN = "// <<< section {sid} — generated by emit.py, edits inside will be overwritten"
END = "// >>> section {sid}"

# Abbreviations that end in a period without ending a sentence.
_ABBREV = {
    "O.G.", "Fig.", "Figs.", "Eq.", "Eqs.", "Sec.", "No.", "Ref.", "Refs.",
    "Dr.", "Mr.", "Mrs.", "St.", "vs.", "etc.", "i.e.", "e.g.", "cf.",
    "approx.", "Inc.", "Co.", "Jr.", "Ch.", "pp.", "Vol.", "C.G.", "O.G.",
}
# Variable-width lookbehind is not allowed, so split first and rejoin after.
_SENTENCE_RE = re.compile(r"(?<=[.!?])[ ]+(?=[A-Z\"'(])")

_FIGURE_RE = re.compile(r"^\s*Figure\s+(\d+)\s*[:.]\s*(.+)", re.S)
_MD_IMAGE_RE = re.compile(r"^\s*!\[(?P<alt>[^\]]*)\]\([^)]*\)\s*$")


@dataclass
class Emitted:
    typst: str
    warnings: list[str] = field(default_factory=list)
    eq_numbers: list[str] = field(default_factory=list)
    unknown: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Prose
# ---------------------------------------------------------------------------

def split_sentences(paragraph: str) -> list[str]:
    """
    One sentence per line — the convention that makes git diffs meaningful.

    Done here rather than asked of the model: the transcriber ignored the
    instruction, and sentence boundaries are a deterministic text operation
    that should not depend on a model's mood.
    """
    text = " ".join(paragraph.split())
    parts = [p.strip() for p in _SENTENCE_RE.split(text) if p.strip()]

    # Rejoin where the split landed after an abbreviation rather than a
    # sentence end — "the forces on the O.G. due to..." is one sentence.
    merged: list[str] = []
    for part in parts:
        if merged and merged[-1].rsplit(" ", 1)[-1] in _ABBREV:
            merged[-1] = f"{merged[-1]} {part}"
        else:
            merged.append(part)
    return merged


def escape_markup(line: str) -> str:
    """
    Escape characters Typst reads as markup at the start of a line.

    A transcribed sentence beginning with "=" becomes a level-1 heading, which
    silently invents a chapter. The same applies to list and enum markers.

    "#" is deliberately NOT escaped: this runs after linkify, so a leading "#"
    is one of our own generated calls. Escaping it turned #ref(<fig:1-5>) into
    \\#ref(<fig:1-5>), which makes the label a second *definition* rather than a
    reference — Typst then reports the label as occurring twice.
    """
    return re.sub(r"^(\s*)([=+]|[-/](?=\s))", r"\1\\\2", line)


def fix_prose(text: str) -> str:
    """Typographic conventions applied to prose runs, outside math."""
    text = re.sub(r"(?<![-\\])--(?!-)", "---", text)   # manuscript uses -- for em dash
    text = text.replace("...", "…")
    return text


def convert_inline_math(text: str, index: dict, warnings: list[str],
                        unknown: list[str], fixes: C.Corrections) -> str:
    """Rewrite $...$ inline spans from LaTeX to Typst, leaving prose alone."""
    def replace(match: re.Match) -> str:
        result = mathconv.convert(match.group(1), index)
        if not result.typst:
            warnings.append(f"inline math not converted: {match.group(1)[:60]}")
            # Raw LaTeX inside $...$ does not compile — Typst reads \D as an
            # escape and leaves "elta". Quote it so the page still builds.
            escaped = match.group(1).replace('"', "'")
            return f'#conflict[#raw("{escaped}")]'
        unknown.extend(result.unknown)
        return f"${fixes.fix_math(result.typst)}$"

    return re.sub(r"(?<!\$)\$([^$\n]+)\$(?!\$)", replace, text)


# Prose mentions that should become Typst references. Only rewritten when the
# target label actually exists in this chapter — a reference to a label that is
# never defined does not compile, and "Chapter 4" cannot be linked while ch4 is
# still empty.
_REF_PATTERNS = [
    (re.compile(r"\b(Sections?)\s+(\d+(?:\.\d+)*)"), "sec", "at"),
    (re.compile(r"\b(Figures?|Figs?\.)\s+(\d+)"), "fig", "at"),
    # Keep the manuscript's own wording and capitalisation for equations —
    # only the number becomes the reference, via the bare-number eqref helper.
    (re.compile(r"\b([Ee]quations?|Eqs?\.)\s+\((\d+[a-z]?)\)"), "eq", "eqref"),
]


def collect_labels(chapter: str, chapter_num: int) -> set[str]:
    """Every label this chapter will define, so references can be checked."""
    labels = {f"sec:{chapter_num}-{sec.id}" for sec in S.sections(chapter)}
    cache = CACHE_ROOT / chapter
    pages = sorted(int(f.name[1:4]) for f in cache.glob("p*.raw.txt"))
    for page in pages:
        text = read_page(cache, page) or ""
        figure = _FIGURE_RE.match(text.strip())
        if figure:
            labels.add(f"fig:{chapter_num}-{figure.group(1)}")
        for block in re.findall(r"\$\$(.+?)\$\$", promote_bare_equations(text), re.S):
            number = re.match(r"\s*(?:\\text\s*\{\s*)?\((\d{1,3}[a-z]?)\)", block)
            if number:
                labels.add(f"eq:{chapter_num}-{number.group(1)}")
    return labels


def linkify(text: str, labels: set[str], chapter_num: int) -> str:
    """Turn prose mentions into references, skipping math spans."""
    def one(chunk: str) -> str:
        for pattern, kind, style in _REF_PATTERNS:
            def replace(match: re.Match) -> str:
                word, number = match.group(1), match.group(2)
                label = f"{kind}:{chapter_num}-{number}"
                if label not in labels:
                    return match.group(0)      # target does not exist; leave prose alone
                if style == "eqref":
                    return f"{word} #eqref(<{label}>)"
                # "Figure 4a" refers to a panel of Figure 4. The @label form
                # would swallow the trailing letter into the label itself
                # (@fig:1-4 + "a" parses as fig:1-4a), so delimit it explicitly
                # whenever an alphanumeric follows.
                tail = match.string[match.end():match.end() + 1]
                if tail.isalnum():
                    return f"#ref(<{label}>)"
                return f"@{label}"
            chunk = pattern.sub(replace, chunk)
        return chunk

    # Never rewrite inside $...$; a reference there would be read as math.
    parts = re.split(r"(\$[^$\n]+\$)", text)
    return "".join(part if part.startswith("$") else one(part) for part in parts)


# ---------------------------------------------------------------------------
# Block classification
# ---------------------------------------------------------------------------

# A display equation the transcriber left undelimited, e.g.
#   (13) \quad m_b = m_0 - m_f
# olmocr wraps most display math in $$...$$ but drops the delimiters when the
# equation number sits in the left margin — so exactly the numbered equations,
# the ones worth having, arrive as plain text.
_BARE_EQ_RE = re.compile(
    r"^[ \t]*(\(\d{1,3}[a-z]?\)[ \t]*(?:\\quad|\\qquad)?[ \t]*[^\n]*"
    r"(?:=|\\frac|\\int|\\sum|\\lim|\\vec)[^\n]*)$",
    re.M)


def promote_bare_equations(text: str) -> str:
    """Wrap undelimited display equations so they take the math path."""
    return _BARE_EQ_RE.sub(lambda m: f"\n$${m.group(1).strip()}$$\n", text)


def read_page(cache: Path, page: int) -> str | None:
    """
    The normalized text for a page, regenerated from the raw capture if needed.

    Only the raw OCR is committed: the .md is a pure derivation of it via
    ocrlib.normalize(), costing nothing and needing no GPU, so keeping both in
    git would be redundant. Regenerating here means a fresh clone can rebuild
    the chapter with no model and no scans.
    """
    md = cache / f"p{page:03d}.md"
    if md.exists():
        return md.read_text().strip()
    raw = cache / f"p{page:03d}.raw.txt"
    if not raw.exists():
        return None
    text = ocrlib.normalize("olmocr", raw.read_text())
    md.write_text(text)
    return text.strip()


def blocks_of(page_text: str) -> list[tuple[str, str]]:
    """Split a page into ('math'|'table'|'prose', content) blocks in order."""
    out: list[tuple[str, str]] = []
    pos = 0
    pattern = re.compile(r"\$\$(.+?)\$\$|(<table>.*?</table>)", re.S | re.I)
    for match in pattern.finditer(page_text):
        before = page_text[pos:match.start()].strip()
        if before:
            out.append(("prose", before))
        if match.group(1) is not None:
            out.append(("math", match.group(1).strip()))
        else:
            out.append(("table", match.group(2)))
        pos = match.end()
    tail = page_text[pos:].strip()
    if tail:
        out.append(("prose", tail))
    return out


def heading_pattern(sec: S.Section) -> re.Pattern | None:
    """
    Match this section's heading as the transcriber rendered it.

    Observed forms, all from ch1: "1.1 Point-Mass and Rigid-Body Dynamics",
    "2.3 Drag and Side Force" alone on a line, "3.1 _Aerodynamic Disturbances_"
    with emphasis markers, and section 3 with its number dropped entirely — so
    the number is optional and the words tolerate underscores between them.
    """
    if not sec.title:
        return None
    words = r"[\s_*]+".join(re.escape(w) for w in sec.title.split())
    return re.compile(
        rf"(?:^|\n)[ \t]*(?:{re.escape(sec.id)}[.:]?[\s]*)?[_*]{{0,2}}{words}[_*]{{0,2}}[.:]?[ \t]*",
        re.I)


def after_heading(text: str, sec: S.Section) -> str:
    """Content from this section's heading onward, heading removed."""
    pattern = heading_pattern(sec)
    if pattern is None:
        return text
    match = pattern.search(text)
    return text[match.end():] if match else text


def before_heading(text: str, sec: S.Section) -> str:
    """Content up to the next section's heading."""
    pattern = heading_pattern(sec)
    if pattern is None:
        return text
    match = pattern.search(text)
    return text[:match.start()] if match else text


def strip_heading(text: str, sec: S.Section) -> str:
    """
    Remove the section heading the transcriber ran into the body text.

    The page image has the heading as its own line, but the transcriber folds
    it into the following paragraph ("2.1 Thrust Thrust is the term applied
    to..."), which would duplicate the heading emit_section already writes.
    """
    # The running chapter title is reprinted at the top of some pages and the
    # transcriber keeps it; it is not body text.
    text = re.sub(r"^\s*[A-Z][A-Z \-'\"]{15,}\n+", "", text)

    if not sec.title:
        return text
    words = [re.escape(w) for w in sec.title.split()]
    pattern = re.compile(
        rf"^\s*(?:{re.escape(sec.id)}\.?\s*)?{r'[\s_*]+'.join(words)}[.:]?\s*",
        re.I)
    return pattern.sub("", text, count=1)


def emit_figure(chapter_num: int, page_text: str, page: int,
                index: dict, warnings: list[str],
                unknown: list[str], fixes: C.Corrections,
                labels: set[str]) -> str | None:
    """A figure page becomes a #figure with the caption transcribed verbatim."""
    match = _FIGURE_RE.match(page_text.strip())
    if match:
        number = match.group(1)
        caption = " ".join(match.group(2).split())
        # Captions contain inline math ("In a time interval $\\Delta t$..."),
        # which must be converted like any other prose or the raw LaTeX
        # reaches Typst and fails to compile.
        caption = fixes.fix_prose(fix_prose(caption))
        caption = linkify(caption, labels, chapter_num)
        caption = convert_inline_math(caption, index, warnings, unknown, fixes)
        # A figure may be cropped into several files — fig1-4(1).png and
        # fig1-4(2).png are the two panels of Figure 4 — so take every match
        # in order rather than assuming one image per figure.
        assets = CHAPTERS_DIR / "../../assets/figures-original"
        stem = f"fig{chapter_num}-{number}"
        found = sorted(
            [p for p in assets.glob(f"{stem}.png")] +
            [p for p in assets.glob(f"{stem}(*).png")],
            key=lambda p: p.name)
        rel_base = "../../assets/figures-original"
        if len(found) == 1:
            art = f'image("{rel_base}/{found[0].name}")'
            todo = ""
        elif found:
            # #figure takes a single body, so stack the panels of a split
            # figure (fig1-4(1).png, fig1-4(2).png) into one block.
            panels = "\n    ".join(f'image("{rel_base}/{p.name}"),' for p in found)
            art = f"stack(dir: ttb, spacing: 1em,\n    {panels}\n  )"
            todo = ""
        else:
            art = (f'rect(width: 100%, height: 4cm, stroke: 0.5pt + gray)[\n'
                   f'    #align(center + horizon)[#text(gray)[missing {stem}.png]]\n  ]')
            todo = f"// TODO crop {stem}.png from the scan\n"
        return (
            f"{todo}#figure(\n"
            f"  {art},\n"
            f"  caption: [CAPTION]\n"
            f") <fig:{chapter_num}-{number}>"
        ).replace("CAPTION", caption)

    if _MD_IMAGE_RE.match(page_text.strip()):
        return (
            f"// TODO figure on page {page}: no caption was transcribed.\n"
            f"// Model described it as: {_MD_IMAGE_RE.match(page_text.strip()).group('alt')[:90]}\n"
            f"#conflict[Figure placeholder — page {page} needs a number and caption.]"
        )
    return None


# ---------------------------------------------------------------------------
# Section emission
# ---------------------------------------------------------------------------

def emit_section(chapter: str, sec: S.Section, index: dict,
                 fixes: C.Corrections, labels: set[str],
                 next_sec: S.Section | None = None) -> Emitted:
    chapter_num = int(re.search(r"\d+", chapter).group())
    cache = CACHE_ROOT / chapter
    warnings: list[str] = []
    eq_numbers: list[str] = []
    unknown: list[str] = []

    # A parent section that begins on the same page as its first child gets no
    # tile of its own, so its heading would never be emitted and <sec:1-2>
    # would not exist for anything to reference. Emit ancestors here.
    lines: list[str] = []
    for ancestor in S.sections(chapter):
        if (sec.id.startswith(ancestor.id + ".")
                and ancestor.start == sec.start):
            lines.append(f"{'=' * (ancestor.level + 1)} {ancestor.title} "
                         f"<sec:{chapter_num}-{ancestor.id}>")
            lines.append("")

    depth = sec.level + 1  # level 1 is the chapter heading itself
    lines += [
        f"{'=' * depth} {sec.title} <sec:{chapter_num}-{sec.id}>",
        "",
    ]

    for page in sec.pages:
        text = read_page(cache, page)
        if text is None:
            warnings.append(f"page {page} not in cache")
            continue
        if not text:
            continue

        # A boundary page belongs to two tiles — section 1 ends on page 8 and
        # section 1.1 begins on it — so split it at the heading instead of
        # emitting the whole page in both, which duplicated every boundary page
        # and left the heading stranded in the body text.
        if page == sec.start:
            text = after_heading(text, sec)
        if next_sec is not None and page == sec.end == next_sec.start:
            text = before_heading(text, next_sec)
        if not text.strip():
            continue
        text = promote_bare_equations(strip_heading(text, sec))
        lines.append(f"// === page {page} ===")

        figure = emit_figure(chapter_num, text, page, index, warnings,
                             unknown, fixes, labels)
        if figure:
            lines.extend([figure, ""])
            continue

        for kind, content in blocks_of(text):
            if kind == "math":
                result = mathconv.convert(" ".join(content.split()), index)
                if not result.typst:
                    warnings.append(f"p{page}: display math not converted: {content[:60]}")
                    lines.extend([f"#conflict[unconverted: `{content[:100]}`]", ""])
                    continue
                unknown.extend(result.unknown)
                result.typst = fixes.fix_math(result.typst)
                if result.eq_number:
                    eq_numbers.append(result.eq_number)
                    lines.append(
                        f'#eq("{result.eq_number}")[$ {result.typst} $] '
                        f"<eq:{chapter_num}-{result.eq_number}>"
                    )
                else:
                    lines.append(f"$ {result.typst} $")
                lines.append("")
            elif kind == "table":
                warnings.append(f"p{page}: HTML table left for manual conversion")
                lines.extend([
                    f"// TODO convert this table to Typst (page {page})",
                    "#conflict[table omitted — see scan]",
                    "",
                ])
            else:
                for para in re.split(r"\n\s*\n", content):
                    para = para.strip()
                    if not para:
                        continue
                    para = fixes.fix_prose(fix_prose(para))
                    para = linkify(para, labels, chapter_num)
                    para = convert_inline_math(para, index, warnings, unknown, fixes)
                    lines.extend(escape_markup(l) for l in split_sentences(para))
                    lines.append("")

    body = fixes.fix_any("\n".join(lines).rstrip() + "\n")
    return Emitted(body, warnings, eq_numbers, unknown)


# ---------------------------------------------------------------------------
# Compile gate
# ---------------------------------------------------------------------------

def chapter_compiles(chapter_path: Path) -> tuple[bool, str]:
    """
    Typeset the real chapter file, not the fragment in isolation.

    Compiling a section on its own gets two things wrong: relative image paths
    resolve against the probe's directory rather than src/chapters, and any
    cross-section reference (@sec:1-2.1 cited from 2.2) looks undefined because
    its target lives in another fragment. The chapter builds in about a second,
    so there is no reason to check anything smaller.
    """
    with tempfile.TemporaryDirectory() as tmp:
        proc = subprocess.run(
            ["typst", "compile", "--root", str(REPO_ROOT),
             str(chapter_path), str(Path(tmp) / "probe.pdf")],
            capture_output=True, text=True, timeout=180,
        )
    return proc.returncode == 0, proc.stderr.strip()


# ---------------------------------------------------------------------------
# Splicing
# ---------------------------------------------------------------------------

def splice(chapter_path: Path, sid: str, body: str,
           order: list[str] | None = None) -> None:
    begin, end = BEGIN.format(sid=sid), END.format(sid=sid)
    block = f"{begin}\n{body}{end}\n"
    src = chapter_path.read_text()
    pattern = re.compile(
        rf"{re.escape(begin)}.*?{re.escape(end)}\n?", re.S)
    if pattern.search(src):
        # Lambda replacement: the emitted Typst contains backslashes (\ line
        # breaks, \quad) which re.sub would read as escape sequences.
        src = pattern.sub(lambda _m: block, src)
    else:
        # Insert in document order rather than appending. Appending makes the
        # chapter order depend on the order sections happened to be emitted —
        # emitting 1.1 before 1 once left section 1's prose stranded after it,
        # which reads exactly like a missing page.
        insert_at = None
        if order and sid in order:
            for later in order[order.index(sid) + 1:]:
                marker = BEGIN.format(sid=later)
                if marker in src:
                    insert_at = src.index(marker)
                    break
        if insert_at is None:
            # Append after the LAST generated block, not at end of file: the
            # chapter may end with hand-written content (the bibliography) that
            # must stay last.
            tail_markers = [src.rindex(END.format(sid=other)) + len(END.format(sid=other))
                            for other in (order or []) if END.format(sid=other) in src]
            if tail_markers:
                at = max(tail_markers)
                src = src[:at] + "\n\n" + block.rstrip() + "\n" + src[at:]
            else:
                src = src.rstrip() + "\n\n" + block
        else:
            src = src[:insert_at] + block + "\n" + src[insert_at:]
    chapter_path.write_text(src)


IMPORT_LINE = (
    '#import "../preamble.typ": conflict, minor, qty, num, eq, eqref, '
    'symbol-table, chapter-setup\n'
    '#show: chapter-setup'
)


def ensure_imports(chapter_path: Path) -> None:
    """
    Guarantee the chapter imports what the emitted Typst uses.

    Typst's #include does not inherit imports from the including file, so each
    chapter needs its own import line even though main.typ already imports the
    preamble — this is why ch3 carries one too.
    """
    src = chapter_path.read_text()
    if "../preamble.typ" in src:
        return
    chapter_path.write_text(f"{IMPORT_LINE}\n\n{src.lstrip()}")


def chapter_file(chapter: str) -> Path:
    return CHAPTERS_DIR / f"{Path(CHAPTER_PDFS[chapter]).stem}.typ"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--chapter", default="ch1", choices=list(CHAPTER_PDFS))
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--section")
    group.add_argument("--all", action="store_true")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the Typst instead of writing it")
    args = ap.parse_args()

    path = chapter_file(args.chapter)
    if not path.exists():
        raise SystemExit(f"No chapter source at {path}")
    ensure_imports(path)
    fixes = C.load(args.chapter)
    index = mathconv.build_symbol_index(symtab.parse(path))

    targets = (S.tiles(args.chapter) if args.all
               else [S.find(args.chapter, args.section)])
    order = [t.id for t in S.tiles(args.chapter)]
    chapter_num = int(re.search(r"\d+", args.chapter).group())
    labels = collect_labels(args.chapter, chapter_num)
    console.print(f"[dim]{len(labels)} labels available for cross-referencing[/]")

    rule_count = len(fixes.math) + len(fixes.prose) + len(fixes.any)
    if rule_count:
        console.print(f"[dim]{rule_count} correction rule(s) loaded[/]")

    for sec in targets:
        following = next((t for t in S.tiles(args.chapter)
                          if t.start > sec.start), None) if args.all else \
                    next((t for t in S.tiles(args.chapter)
                          if t.start > sec.start), None)
        result = emit_section(args.chapter, sec, index, fixes, labels, following)

        if args.dry_run:
            ok, err = True, ""
        elif args.all:
            # Gate once at the end: section 2.3 cites @fig:1-8, which section 3
            # defines, so a per-section check would fail on every forward
            # reference no matter what order sections are written in.
            splice(path, sec.id, result.typst, order)
            ok, err = True, ""
        else:
            before = path.read_text()
            splice(path, sec.id, result.typst, order)
            ok, err = chapter_compiles(path)
            if not ok:
                path.write_text(before)   # roll back; the chapter always compiles

        status = "" if args.all else (
            " — [green]compiles[/]" if ok else " — [red]DOES NOT COMPILE[/]")
        console.print(f"\n[bold]{sec.id}[/] {sec.title} "
                      f"(p{sec.start}–{sec.end}){status}")
        if result.eq_numbers:
            console.print(f"  equations numbered: {', '.join(result.eq_numbers)}")
        if result.unknown:
            console.print(f"  [yellow]not in symbol table: "
                          f"{', '.join(sorted(set(result.unknown)))}[/]")
        for warning in result.warnings:
            console.print(f"  [yellow]![/] {warning}")

        if args.dry_run:
            console.print(result.typst)
            continue
        if not ok:
            first = next((l for l in err.splitlines() if l.strip()), "")
            console.print(f"  [red]rolled back.[/] {first}")
            continue
        console.print(f"  written to {path.name}")


    if args.all and not args.dry_run:
        ok, err = chapter_compiles(path)
        if ok:
            console.print("\n[green]chapter compiles[/]")
        else:
            console.print("\n[red]CHAPTER DOES NOT COMPILE[/]")
            for line in err.splitlines()[:12]:
                console.print(f"  {line}")

    if fixes.hits:
        console.print("\n[bold]corrections applied[/]")
        for find, n in sorted(fixes.hits.items(), key=lambda kv: -kv[1]):
            console.print(f"  {n:4d}x  {find!r}")


if __name__ == "__main__":
    main()
