#import "../preamble.typ": conflict, minor, qty, num, eq, eqref, symbol-table, chapter-setup
#show: chapter-setup

= An Introduction to the Dynamics of Model Rocket Flight <flight-dynamics>

#table(
      columns: (1fr, 2fr),
      align: horizon,
      stroke: none,
      // inset: (x: 8pt, y: 3pt),
      table.hline(),
      table.header(
        table.cell()[Symbol],
        table.cell()[Meaning]
      ),
      table.hline(stroke: 0.5pt),
      [$A$], [coefficient used in writing example of $F(t)$],
      [$A_r$], [reference area],
      [$C$], [constant of integration],
      [$C_D$], [drag coefficient],
      [$C_D_0$], [coefficient of drag at zero angle of attack],
      [$C_n$], [normal force coefficient],
      [$D$], [drag],
      [$F$], [magnitude of thrust, whose direction is assumed to be forward along the vehicle centerline],
      [$arrow(F)$], [thrust],
      [$F(t)$], [thrust as a function of time],
      [$F_(a v)$], [average thrust],
      [$F_1, dots.h, F_8$], [thrust values used in computing total impulse by approximate summation method],
      [$I_(s p)$], [specific impulse],
      [$I_t$], [total impulse],
      [$L$], [characteristic length],
      [$N$], [normal force],
      [$R$], [radius measured from the center of the earth],
      [$R_e$], [Reynolds number],
      [$R_0$], [radius of the Earth],
      [$S$], [side force],
      [$c$], [magnitude of exhaust velocity, whose direction is assumed to be rearward along the vehicle centerline],
      [$arrow(c)$], [exhaust velocity],
      [$dif (space.en)$], [differential of $(space.en)$],
      [$(dif (space.en))/(dif t)$], [derivative of $(space.en)$ with respect to time],
      [$f ( )$], [function of angle of attack],
      [$g$], [magnitude of acceleration of Earth's gravity],
      [$arrow(g)$], [acceleration of Earth's gravity],
      [$g_0$], [value of $g$ at sea level],
      [$k$], [parameter of drag at zero angle of attack],
      [$m$], [mass],
      [$m_b$], [burnout mass],
      [$m_f$], [propellant mass],
      [$m_0$], [initial mass],
      [$dot(m)$], [mass flow rate],
      [$Delta m_e$], [increment of mass added to the exhaust stream],
      [$Delta m_r$], [change in mass of rocket],
      [$n$], [exponent of $t$ used in writing example of $F(t)$],
      [$t$], [time],
      [$t'$], [time at which a time-derivative is computed],
      [$Delta t$], [interval of time],
      [$Delta t_1, dots.h, Delta t_8$], [time intervals used in computing total impulse by approximate summation method],
      [$t_b$], [burn time],
      [$v$], [magnitude of velocity; _also_ airspeed],
      [$arrow(w)$], [weight],
      [$w_f$], [weight of propellant charge],
      [$x$], [horizontal coordinate, range],
      [$y$], [vertical coordinate, altitude],
      [$Delta (space.en)$], [increment of $(space.en)$, change in $(space.en)$],
      [$Delta (space.en)$], [sum of all $(space.en)$],
      [$alpha$], [angle of attack],
      [$epsilon$], [parameter of drag due to angle of attack],
      [$mu$], [absolute viscosity],
      [$nu$], [kinematic viscosity],
      [$rho$], [mass density],
      [$lim_(n -> infinity)$], [limit as $n$ approaches infinity],
      [$integral [space.en] dif(space.en)$], [integral of $[space.en]$ with respect to $(space.en)$],
      table.hline()
    )

// <<< section 1 — generated by emit.py, edits inside will be overwritten
== Definition of the Problem <sec:1-1>

// === page 6 ===
There is probably not a single model rocketeer in the world who has not, at one time or another, found himself speculating on the subject of model rocket flight performance.
How high, how fast will a rocket go?
Will it fly straight and true or not?
Will it "weathercock" --- that is, fly into the wind?
Will it wobble on the way up?
How high will it go if launched at an angle, and how far?
Such questions as these are the most natural and common that come to mind when one is presented with a new rocket design.
They are of interest to even the most casual sport flyer, and of course are the vital concerns of competition rocketeers and researchers.
It is the purpose of this book to present information that will enable any interested model rocketeer with a reasonably complete educational background to answer them accurately and completely, using the most advanced and general methods available in our hobby to date.

The mathematical equations that would have to be solved to compute theoretically exact answers to the questions of model rocket flight performance are among the most difficult known to the physical sciences.
Complete, exact, and unique solutions to these equations have never been obtained by anyone, whether model rocketeer or professional scientist.

// === page 7 ===
As do professional scientists and engineers, therefore, we shall formulate the problems subject to certain simplifying approximations and assumptions that will permit them to be solved to a high order of accuracy.
Such approximations make solutions possible but this still gives us no right to expect them to be easy, and indeed we invariably find that they are quite difficult to obtain in "closed form" --- that is, a form which can be expressed by a single algebraic formula; not, for instance, a graph, a table, or an infinite series.
This is because the most liberal approximations that are possible without badly degrading the accuracy of the desired solution still cannot alter the fact that the equations describing the motion of a model rocket at any given instant during its flight are of a type called differential equations, and as such cannot be solved without the methods of differential and integral calculus.
We have used these methods extensively in compiling the material used in this book and have used the various notations of calculus freely in describing the steps by which flight performance solutions are obtained, both for the interest of those advanced rocketeers who are familiar with calculus and because there is simply no other way of discussing these matters accurately.
We know very well, however, that only a small fraction of our readers can be expected to have any knowledge of advanced mathematics, and we have adjusted our presentation accordingly.
You should not, therefore, become discouraged if you cannot follow the various mathematical treatments describing how the solutions are obtained.
As a practical model rocketeer you will be most

// === page 8 ===
interested in the final results of these presentations --- the solutions themselves.
And in every case you will find that these solutions can be worked out numerically using relatively simple numerical substitutions in the algebraic formulæ which have been obtained, plus a handbook of mathematical tables.

In this chapter the general problem of computing model rocket flight performance will be considered, and the various techniques used to cast these problems into forms capable of closed-form, analytic solution will be discussed.
The forces which influence the motion of model rockets will be briefly described and the methods by which the performance problems will be attacked in subsequent chapters will be introduced, while the presentation of the detailed solutions themselves will be left for the chapters reserved for them.
// >>> section 1

// <<< section 1.1 — generated by emit.py, edits inside will be overwritten
=== Point-Mass and Rigid-Body Dynamics <sec:1-1.1>

// === page 8 ===
The problem of computing in detail the motion of a model rocket in flight is one of analytical dynamics and kinematics.
By "kinematics" is meant the mathematical study of movement itself, while "dynamics" can, for the purposes of this book, be taken to mean the physical and mathematical study of the relationships between movement and the various forces and moments which produce it.
In general, one can distinguish two classes of motion of which rigid, extended bodies are capable: the translational motion of the body considered as a point mass concentrated at its center of mass and the rotational motion described by the body about its center of mass.
Since, for all purposes of interest to model rocketeers, the center of

// === page 9 ===
mass of an object can be considered equivalent to its center of gravity, the notation C.G. will hereafter be used to refer to a model rocket's center of mass or center of gravity.
The concepts of translation and rotation are illustrated by example in @fig:1-1.

In the absence of any physical interrelation between the motion of the C.G. itself and the rotation of the model about its C.G. the differential equations describing the rocket's motion would possess a certain very useful and valuable property: the equations describing the rigid-body rotations would be decoupled from those describing the point-mass motions.
That is to say that, if the rotation of the model about its C.G. in flight did not affect the net forces acting on it, and if the translational motion of the rocket as a point mass did not affect the moments tending to rotate the model about its C.G., the equations of motion of the C.G. and the equations of motion for the rigid-body rotations could be solved independently of one another.
The practical effect of such a state of affairs would be to greatly simplify the mathematics involved, since the translational motion could be solved while ignoring rotation and the rotational motion could be solved while ignoring translation.

For any extended body moving through the atmosphere in the Earth's gravitational field, however, there are external forces and moments which couple the rigid-body rotation to the C.G. translation.
These external forces and moments arise from the various components of atmospheric resistance, or drag.

// === page 10 ===
#figure(
 image("../../assets/figures-original/fig1-1.png"),
 caption: [Translational and rotational motion. The center of gravity of the rocket in illustration (a) has translated from position 1 to position 2; the rocket has not rotated at all during the motion. The rocket of illustration (b) has rotated from position 1 to position 2 about its center of gravity without undergoing any translation.]
) <fig:1-1>

// === page 11 ===
acting on the body which affect both the C.G. motion and the rigid-body motion.
If the model should undergo rigid-body motion due to aerodynamic or other forces, the changes in its angle to the incident airflow resulting from such motion will change the drag experienced by the vehicle, thus affecting the total force on it.
In the presence of gravity, the rigid-body rotations will also change the angle of the thrust vector with respect to the local vertical and will therefore change the vertical and horizontal components of the force on the model due to the thrust.
The point-mass motion also influences the rigid-body motion, since the magnitude of the drag components which act to rotate the vehicle vary strongly with the velocity of the C.G. The differential equations of motion of a model rocket travelling through the atmosphere under the influence of gravity are, therefore, a coupled set of equations.
// >>> section 1.1

// <<< section 1.2 — generated by emit.py, edits inside will be overwritten
=== Separation of the Differential Equations of Motion <sec:1-1.2>

// === page 11 ===
Since, as we have remarked, it is generally much easier to solve a system of mutually independent equations than it is to solve a coupled set, the authors of the various chapters have followed the procedure generally used in full-scale science and engineering for problems of this type by adopting various simplifying approximations which permit the point-mass and rigid-body equations of motion to be decoupled (and also greatly simplify the solution of each of the decoupled sets).
Such a separation cannot result in exact solutions; it will yield solutions of acceptable accuracy only if the coupling between the two types of motion is slight or "weak" in some sense.

// === page 12 ===
The analyses of model rocket flight presented in this book will therefore be restricted to cases of weak coupling.
As will be shown in Chapter 2, and later in Chapter 4, the coupling is in fact slight for all rockets that can be considered well-designed, so such a restriction is not unreasonable.
One may therefore decouple the equations of motion under the assumption that the forces on the O.G. due to the rigid-body rotations are small compared to the other forces influencing the point-mass motion.

Once the separate solutions to the decoupled equations of motion have been obtained, approximate methods will be used to re-introduce coupling for the purpose of obtaining a "first-order" idea of the effect of rigid-body motions on the altitude capability of any given model rocket.

The remaining sections of this chapter will be devoted to brief discussions of each of the forces and moments which influence the rigid-body and point-mass motion of model rockets.

2.
Description of the Flight Forces This section will enumerate and consider the forces on the model which give rise to the motion of its center of mass.
Such forces will hereafter be referred to as flight forces, as opposed to those forces encountered during the course of a model's flight whose moments give rise to rigid-body rotations.
These latter forces will be referred to as perturbing forces.
// >>> section 1.2

// <<< section 2.1 — generated by emit.py, edits inside will be overwritten
== Descriptions of the Flight Force <sec:1-2>

=== Thrust <sec:1-2.1>

// === page 12 ===
is the term applied to the force produced by a model rocket engine due to the rapid exit of exhaust gases

// === page 13 ===
from its nozzle.
The engine itself is no more than an enclosed furnace in which the fuel is burned to produce a hot gas which then exits under extreme pressure from a small nozzle specially shaped so as to produce the greatest possible velocity of the exhaust stream.
A chemical rocket, however, is a highly specialized type of furnace in that the oxygen required for the combustion of the fuel is obtained not from the air, but from an oxygen-rich chemical, or _oxidizer_, carried along with the fuel in the rocket itself.
For this reason a rocket will continue to burn in the vacuum of outer space, and hence chemical rockets are used in spaceflight.
In the case of the solid-propellant model rocket engine the fuel and oxidizer are mixed together to form a homogeneous _propellant grain_.

To gain some understanding of how a rocket engine produces thrust, suppose we examine the hypothetical rocket of @fig:1-2, which is emitting gas at a constant exhaust velocity of magnitude c in the negative y direction.
In some short interval of time, say $Delta t$, a mass of exhaust gas $Delta m_e$ leaves the nozzle, so that the mass of the rocket engine changes by the amount $Delta m_r = -Delta m_e$.
If the time interval is permitted to become so short as to be what mathematicians refer to as _infinitesimal_ it may be denoted by dt, also referred to in the language of calculus as the _differential_ of time.
In this case the mass change experienced by the rocket will also become so small as to be considered a differential quantity, denoted by $-dot(m)_e$.
The instantaneous rate at which the mass of the rocket is changing is then given by the ratio of the differential mass change to the differential

// === page 14 ===
#figure(
 image("../../assets/figures-original/fig1-2.png"),
 caption: [Origin of rocket thrust. In a time interval $Delta t$ the rocket expels the quantity of mass $Delta m_e$ at the exhaust velocity $arrow(c)$ in the (-y) direction. "In the limit" as $Delta t$ becomes $dif t$ and $Delta m_e$ becomes $dif m_e$ the rate of mass expulsion --- or "mass flow rate" --- is $(dif m_e)/(dif t)$ (also written $dot(m)$). The thrust $arrow(F)$ is given by the equation $arrow(F) = -arrow(c)((dif m_e)/(dif t))$ and thus acts in the (+y) direction.]
) <fig:1-2>

// === page 15 ===
time interval over which that change occurs.
This ratio is also called the derivative of the rocket's mass with respect to time:

rate of mass change = \frac{-d m_e}{dt}

\= derivative of mass with respect to time

The above explanation of the derivative as a ratio of differentials is useful in forming a mental picture of what a derivative physically represents, but it provides no information about how derivatives are actually computed.
They are not calculated by somehow finding each differential and taking the ratio of the two; they are, rather, done "all at once" by one of two possible methods.
The first such method is usable when the dependent variable (in this case mass) is given as an analytic function of the independent variable (in this case time); that is, when the dependent variable is expressed as some algebraic formula in terms of the independent variable.
In such cases the derivative is itself an algebraic formula which is computable from the original function by means of the limiting arguments used in differential calculus.
You will not need to know how to perform any such calculations to understand this book; wherever the derivative of an algebraic expression is needed we will supply it already written out.
The second method is an approximate one and is used when the function whose derivative is to be taken is supplied in graph or table form.
In the case of a graph, the derivative at any given time t' is just the slope of the tangent line touching the graph at

// === page 16 ===
that value of time.
The meaning of these terms is indicated by the example in @fig:1-3, which also describes the procedures for obtaining derivatives from graphs and tables.

Now the connection between the time derivative of a rocket's mass and the thrust of its engine lies in the fact that the thrust of a rocket motor is equal to the rate at which it is transferring momentum to the rocket in which it is mounted.
Those of you who have had some exposure to elementary physics will be familiar with the concept of momentum; some of you, moreover, may already know that the rate of momentum transfer resulting from the expulsion of mass from a body depends upon two quantities: the rate at which mass is being expelled and the velocity with which it is being ejected.
In Chapter 4 it will be shown by more detailed momentum considerations that the relationship involved is

$ arrow(F) = -arrow(c) (dif m_e)/(dif t) $

where $arrow(F)$ denotes the thrust produced by the motor and $arrow(c)$ is the velocity of the exhaust gases as measured by an observer moving with the rocket.
Both the thrust force and the exhaust velocity, students of physics will note, are vector quantities; that is, both their magnitudes and the directions in which they act must be specified to describe them completely.
Mass (and its time derivative), on the other hand, is a scalar quantity; it can have only a magnitude.

In a properly designed and constructed model rocket whose engine is not suffering from any malfunction the exhaust stream

// === page 17 ===
#figure(
 image("../../assets/figures-original/fig1-3.png"),
 caption: [The concept of a derivative, as illustrated by the rate of mass change of a model rocket engine due to the expulsion of exhaust gases. Two approximate methods for the computation of derivatives are illustrated: graphical solution by the use of a "tangent" line (a) and numerical solution using a table (b). Note that $Delta m$ is negative because mass _decreases_ as time _increases_. $(dif m)/(dif t)$ as illustrated here is just the negative of $(dif m_e)/(dif t)$.]
) <fig:1-3>

// === page 18 ===
is directed dead astern.
In such a case we can replace the full vector notation for force and velocity with a simpler, fore-and-aft sign convention in which vector quantities directed forward along the vehicle longitudinal axis are considered positive, while those directed rearward are considered negative.
According to this convention.

$ arrow(c) equiv -c $

so that

$ F = c (dif m_e)/(dif t) $

Professional rocket engineers refer to the derivative $(dot(m)_e)/(dif t)$ as the mass flow rate and sometimes write it as $dot(m)$, the superscript dot denoting differentiation with respect to time (an alternate calculus notation for the time derivative which is sometimes used to save writing).
Note that, since positive quantities only are involved in the right-hand side of equation (2), the thrust is a positive quantity also --- confirming what we as practical model rocketeers already know to be the case; namely that the thrust is directed forward along the rocket's centerline.

// === page 19 ===
In theory, then, if you were given the exhaust velocity and mass flow rate of any given rocket motor as functions of time, you could compute the thrust of that motor as a function of time.
It is also theoretically possible to calculate both the exhaust velocity and the mass flow rate from the combustion characteristics and thermodynamic properties of the propellant and the size and shape of the combustion chamber and the nozzle.
In practice, however, rocket engineers generally compute the thrust directly from the propellant, casing and nozzle characteristics and obtain the exhaust velocity and mass flow rate as byproducts of this calculation.
The thrusts of model rocket engines as functions of time are always supplied by the manufacturers in graphical form: the so-called thrust-time curves, which are derived from averaging a large number of traces recorded during static firings of engines of the same type.
The thrust-time curves of individual model rocket motors may differ somewhat from the average for their type.
This variation is not too severe, however, in motor types which have received Safety Certification or Contest Certification from the Standards and Testing Committee of the National Association of Rocketry.

In any one given engine, one generally finds that variations in thrust with time are due more to variations in the mass flow rate than variations in the exhaust velocity.
In fact, it is almost always accurate enough for model rocketry purposes to assume the exhaust velocity to be constant during the entire burning period.
The mass flow rate can then be easily computed from equation (2) if you are careful with units.
Suppose, for

// === page 20 ===
instance, that the thrust is given in newtons and the exhaust velocity in meters/second.
Remembering that one newton is one kilogram-meter/(second^2), one then obtains the mass flow rate in kilograms/second, which can easily be converted to grams/second by multiplying by a thousand.
An easy method of calculating the average exhaust velocity will be described a little later on.

Model rocket engines come in a wide variety of sizes and configurations, permitting the modeler to choose any desired average thrust from as low as 3 newtons to as high as 100 newtons.
A knowledge of the average thrust alone, however, is not sufficient to enable one to predict the overall effect of the engine on the rocket's performance.
It is also necessary to know how the thrust varies as a function of time and the length of time for which the engine will burn.
Knowing these the modeler can compute the total momentum change which the engine will impart to the rocket, also called the total impulse, according to the relation

$ I_t equiv integral_0^(t_b) F(t) dif t $

where $I_t$ is the total impulse, $F(t)$ is the calculus notation for "thrust as a function of time", and $t_b$ is the total burning time (not counting the delay/tracking charge) of the engine.
Equation (3) is the first we have encountered so far needing the techniques of integral calculus for its solution.
The symbol $integral$ is referred to as an integral sign.
The quantity to be "integrated" (in this case $F(t)$) is called the integrand, and the variable with respect to which the integration is to be

// === page 21 ===
performed; that is, the independent variable (in this case time, or t) is referred to as the variable of integration, or running variable.
The differential of the running variable is always written after the integrand to identify the running variable; hence the "dt" after F(t).
The time values 0 and t_b are the limits of integration, and the integration is said to be performed between 0 and t_b, or from 0 to t_b.

As far as model rocketeers are concerned there are two ways in which an actual number for I_t can be obtained from equation (3).
The first of these can be used only if F(t) is given by some well-defined algebraic formula, in which case mathematicians have shown that there also exists an algebraic formula for $integral F(t) dif t$ (the integral written without limits is called an "indefinite integral" and is used to refer to the general functional form of the integral as opposed to the integral written with limits, or "definite integral", which refers to the actual value of the integral taken between specific limits).
The integrals of a great many specific functions have been tabulated and listed in such books as Burington's Handbook of Mathematical Tables and Formulas and the CRC Standard Mathematical Tables, which are used as references by students of science and engineering.
For instance, if the functional form of F(t) is given by

$ F(t) = A t^n $

where A and n are constants, then

$ integral F(t) dif t = A/(n+1) t^(n+1) + C $

// === page 22 ===
where $C$ is a "constant of integration" which must generally be determined by physical considerations called the "initial conditions" of the problem.
Of particular interest is the case $n = 0$, which describes a thrust that is constant over the burn time:

$ F(t) = A t^0 \ = A $

Then

$ integral F(t) dif t = A t + C $

It will be found that, in all problems of computing total impulse, $C$ is zero.
Now it is a basic rule of calculus that the value of a definite integral is equal to the value of the integral taken at the upper limit _minus_ the value taken at the lower limit.
That is, in this case,

$ integral_0^(t_b) F(t) dif t = [A t]_(t=t_b) - [A t]_(t=0) \ = A t_b - A dot.op 0 \ = A t_b $

So you can see that for the case of constant thrust the total impulse is just equal to the thrust multiplied by the burn time.
In fact, the total impulse is always equal to the _average_ thrust multiplied by the burn time, but for all cases other than that of constant thrust the average thrust itself must be calculated from the total impulse, which has been determined from (3), according to

$ F_(a v) = I_t / t_b $

// === page 23 ===
You can also see that total impulse has units of (force x time).
Since model rocket thrust is measured in newtons and time in seconds, total impulse is given in newton-seconds.

But suppose there is no simple algebraic formula that describes F(t).
Suppose there is either no known formula at all or one so complicated that its integral would literally cover pages.
In such cases the total impulse can be computed numerically, without integral formulae.
To see how this is done suppose we take as an example the thrust-time curve of #ref(<fig:1-4>)a, which is typical of many of the smaller classes of model rocket engines: there is an initial "spike" at ignition followed by a drop-off to a fairly constant thrust for the rest of the burn time.
In #ref(<fig:1-4>)b the exact thrust-time curve has been approximated by a series of eight adjacent rectangles.
There are many mathematically "fancier" and more precise ways to do this, but in #ref(<fig:1-4>)b it has been done "by eye" and indeed such an intuitive, physical approach will be found sufficiently accurate for virtually all model rocketry work.
The total impulse according to this method is given approximately by

$ I_t approx F_1 Delta t_1 + F_2 Delta t_2 + F_3 Delta t_3 + F_4 Delta t_4 + F_5 Delta t_5 + F_6 Delta t_6 + F_7 Delta t_7 + F_8 Delta t_8 $

It is evident that more than eight rectangles can be used, and that the approximation will get better as the number of rectangles increases and they get narrower and narrower.
"In the limit", as the rectangles get infinitesimally thin, the approximation will become exact --- and in fact this is just the definition of

// === page 24 ===
#figure(
 stack(dir: ttb, spacing: 1em,
 image("../../assets/figures-original/fig1-4(1).png"),
 image("../../assets/figures-original/fig1-4(2).png"),
 ),
 caption: [Total impulse and the concept of integration. Panel (a) shows the thrust-time curve of the NAR Type B4 engine. The total impulse $I_t$ of the engine is equal to the integral of its thrust-time curve; that is, to the area (in N-sec) enclosed by it. The other three panels show some approximate methods of obtaining this integral. In (b) the curve has been approximated by a series of rectangles and $I_t$ has been computed as the sum of the areas (in N-sec) of the rectangles. In (c) each square of the grid represents 0.1 N-sec and $I_t$ is found by determining the approximate number of squares enclosed by the curve. In (d) the weight in gram-forces of a piece of cardboard 1 sec long and 1 N high has been determined and $I_t$ has been found by comparing it with the weight of a cardboard cutout of the curve. Method (d) was most accurate in this case, as the actual $I_t$ of the B4 engine is 5.0 N-sec.]
) <fig:1-4>

// === page 25 ===
I_t = 49.7 \times 0.1 = 4.97 \text{ N-sec}

0.38 g = 1.0 \text{ N-sec}

1.90 g = 5.0 \text{ N-sec}

![Graph showing F(t) vs t (sec) with labeled area 4.97 N-sec](page_120_120_320_320.png)

![Graph showing two labeled areas: 0.38 g = 1.0 N-sec and 1.90 g = 5.0 N-sec](page_520_120_320_320.png)

// === page 26 ===
the integral as used in calculus, for which the mathematical notation is

$ lim_(n -> infinity) sum_(i=1)^n F_i Delta t_i = integral_0^t F(t) dif t $

A similar numerical method consists of "counting the squares on the graph paper" enclosed by the thrust-time curve and the axes.
The number of newton-seconds represented by each square can be found from a knowledge of the vertical and horizontal graph scales.
The impulse per square is then multiplied by the number of squares to give the total impulse, as shown in #ref(<fig:1-4>)c.
An instrument called a planimeter is often used to compute total impulse in this manner.
The instrument has a stylus which is used to trace the boundary of the thrust-time curve, resulting in a measurement of the area enclosed by the curve.
The total impulse is directly proportional to this area, the constant of proportionality being equal to the amount of impulse represented by a unit area of the graph paper.
Persons who do not have a planimeter can still make a good planimetric determination of total impulse using the method of #ref(<fig:1-4>)d.
In this technique the thrust-time curve is traced onto cardboard, cut out, and weighed on a good laboratory gram balance.
A rectangle of the same kind of cardboard cut to the size that represents a single newton-second of impulse in the scale to which the thrust-time curve is drawn is also weighed.
The weight of the curve cutout divided by the weight of the one newton-second rectangle is then equal to the total impulse.
You can see that all these numerical methods rely on the

// === page 27 ===
essential relationship between the integral of a function and the area enclosed between the graph of that function and the coordinate axes with respect to which that graph is drawn.
Appeals to the intuitive notion of an integral as "the area under the curve" of the integrand are in fact often used in teaching calculus at the senior high school and undergraduate college level.

The particular functional forms of F(t) encountered in model rocketry fall into several well-defined classes.
These categories are represented by the sample thrust-time curves of #ref(<fig:1-5>)a, 5b, and 5c.
The curve of #ref(<fig:1-5>)a exemplifies the behavior of a typical end-burning motor.
The vast majority of the NAR Class 1A through D engines, as well as some of the larger engines, have thrust-time curves of this type.
Such engines are produced with a solid propellant grain having a slight indentation at the rear, immediately inside the nozzle.
The indentation serves a dual purpose: it provides a convenient cavity into which the electrical igniter may be packed and it is also responsible for increasing the burning surface area of the propellant grain in the fraction of a second immediately following ignition, thereby producing the "spike" in the thrust-time curve shown in #ref(<fig:1-5>)a.
This short period of higher thrust is useful in accelerating the model rapidly to velocities at which the stabilizing fins become effective.
Thereafter the thrust decreases to the virtually constant level characteristic of a true end-burning, or "cigarette-burning", grain until burnout occurs.

// === page 28 ===
#figure(
 image("../../assets/figures-original/fig1-5.png"),
 caption: [Major classes of model rocket thrust-time curves. (a): Curve of Type B4 engine, representative of end-burning engines with initial peak. (b): Curve of Type B14 engine, a core-burning engine with a constant-diameter port. (c): Curve of Type E62 engine, an ammonium perchlorate/polyurethane engine also having a constant-diameter port. Its high-energy propellant is slow-burning, enabling it to produce thrust-time characteristics that would require a tapered port in a blackpowder engine.]
) <fig:1-5>

// === page 29 ===
#ref(<fig:1-5>)b represents the thrust-time curve of the NAR type Bl4 motor, a high-thrust, short-time engine used to accelerate heavy rockets and multistaged models.
These engines have a hollow core, or port, along the central axis of the grain, causing burning to progress radially outward toward the wall of the casing rather than forward as in the end-burning motors.
The burning surface area of the core-burning motor is thus much greater than that of the end-burner and its thrust-time curve consists of a single, high-thrust spike.
The rapidity with which these engines can accelerate a model has been described by stating that they deliver a "sledge-hammer blow" or "kick in the tail" to the rocket in which they are installed.

Many of the largest model rocket engines --- those in NAR Classes E and F --- have thrust-time curves like that of #ref(<fig:1-5>)c.
These engines are also port-burners but, unlike the Bl4, they have tapered ports; their grain configurations are said to be "three-dimensional".
Although they also exhibit a characteristic peak in their thrust-time behavior, this peak is attained more gradually than is the case with the Bl4 engines and occurs near the end of the burning period.

Since the invention of the rocket in China during the Middle Ages a great many varieties of solid propellant have been developed.
The first rockets used black gunpowder, an improved form of which is still the major constituent of most model rocket propellants.
Smokeless powder was introduced at the beginning of the twentieth century, followed by "double-base" propellants --- essentially variations of nitroglycerin- and nitrocellulose-type compounds --- and "composite" propellants

// === page 30 ===
like the polyurethane/ammonium perchlorate mixtures used in the Polaris and Minuteman guided missiles and many sounding rockets currently in use.
When selecting a propellant from among the many available types, one of the first questions the rocket engineer asks is, "How powerful is it?" The answer to this question lies in a quantity called the _specific impulse_ of the propellant; that is, the total impulse obtainable from the combustion of a unit mass of propellant.
Specific impulse is thus a measure of a propellant's efficiency.
Strictly speaking, the mathematical definition of specific impulse is

$ I_(s p) = (I_t)/(m_f) $

where $m_f$ is the mass of propellant consumed in providing the total impulse $I_t$.
The strictly consistent physical units for $I_(s p)$ in the MKS system used in model rocketry are therefore newton-seconds per kilogram.
Rocket engineers, however, use _weight_ measure when computing specific impulse, using the definition

$ I_(s p) = (I_t)/(w_f) $

where $w_f$ is the _weight_ of propellant required to produce the total impulse $I_t$.
According to this definition $I_(s p)$ has units of newton-seconds per newton --- or simply _seconds_.
The engineering definition is especially convenient in that it relates $I_(s p)$ to the exhaust velocity through the simple relation

$ c = g I_(s p) $

// === page 31 ===
where g is the acceleration of the Earth's gravity field (9.8 meters/sec.2).

Model rocket engines using pressed blackpowder propellant grains exhibit values of specific impulse in the range of 48 to 103 seconds.
More recently, several types of engines using high-performance, ammonium perchlorate/polyurethane propellants have been introduced in model rocketry.
These motors deliver specific impulses in the neighborhood of 175 seconds.
There exist solid propellants which deliver specific impulses in excess of 240 seconds when burned at high chamber pressures, but problems of temperature, pressure, ignition technology, and cost have so far prevented their use in model rocketry.

The specific impulse delivered by any given model rocket motor is a quantity that is measured and published, either by the manufacturer of that motor himself or by the NAR Standards and Testing Committee.
It is therefore a simple matter to compute the average exhaust velocity of any given motor using equation (7), and to use the value of exhaust velocity thus obtained in computing the mass flow rate from equation (2) and a knowledge of the engine's thrust-time curve.
// >>> section 2.1

// <<< section 2.2 — generated by emit.py, edits inside will be overwritten
=== Weight <sec:1-2.2>

// === page 31 ===
The weight of a model rocket is the force exerted on it by the Earth's gravitational field.
A rocket of mass m will have a weight given by

$ arrow(w) = m arrow(g) $

where, as before, $arrow(g)$ is the (vector) acceleration of the Earth's

// === page 32 ===
gravity field.
The weight force always points in the direction of the gravity field, which in this case is the center of the Earth --- or "straight down" along the local vertical.
Strictly speaking, the value of $arrow(g)$ decreases with increasing altitude above the Earth's surface according to the relation

$ g/(g_0) = [ (R_0)/R]^2 $

where $R_0$ is the radius of the Earth, $g_0$ is the magnitude of $arrow(g)$ at the Earth's surface, $R$ is any radius greater than $R_0$ and $g$ is the magnitude of $arrow(g)$ at that radius.
Even a 20,000-foot model rocket flight (about 6,000 meters --- much higher than any ever officially confirmed), however, would result in an apogee value of $R$ only one tenth of one percent greater than $R_0$.
The effect of altitude on the weight of a model rocket is, therefore, wholly negligible.
In all the calculations in this book $arrow(g)$ will be taken to have the magnitude $g_0$.

The weight of a model rocket does vary during its flight, though.
This in-flight weight variation is due to the expulsion of mass from the rocket motor as it produces thrust.
In @sec:1-2.1 the relationship between thrust and the rate of mass expulsion was established as equation (2).
Equation (2) can now be used to determine the model's mass as a function of time in the form

$ m = m_0 - integral_0^t F(t)/c dif t $

When the engine ceases burning at time $t_b$, the mass of the rocket is

// === page 33 ===
#eq("11")[$ m_b = m_0 - integral_0^(t_b) F(t)/c dif t "or, since" $] <eq:1-11>

#eq("12")[$ m_f = integral_0^(t_b) F(t)/c dif t $] <eq:1-12>

where $m_f$ is the total mass of propellant in the engine before ignition,

#eq("13")[$ m_b = m_0 - m_f $] <eq:1-13>

Accordingly, the weight of the rocket decreases continuously during the engine burn and the model is lighter after burnout than at ignition.
In large guided missiles and space boosters the propellant constitutes most of the liftoff mass of the vehicle, so that such a rocket at burnout has only a small fraction of the mass it had at ignition.
In model rockets, however, the mass change due to the expenditure of the propellant is relatively slight.
This fact, as will be shown in Chapter 4, considerably simplifies the calculation of model rocket altitude performance.

Unlike the thrust, the direction of the weight vector remains invariant when the rocket rotates or "tips" away from the vertical.
The weight of a model rocket, or for that matter any object, appears to originate from a point called the center of mass, which for all practical purposes within the scope of this book may be taken as identical to the center of gravity, or balance point: the point by which the object may be suspended without showing any tendency to rotate in any direction.
All rotations of a model in flight occur about the C.G., and the weight vector always acts through the C.G. downward along the local vertical.
// >>> section 2.2

// <<< section 2.3 — generated by emit.py, edits inside will be overwritten
=== Drag and Side Force <sec:1-2.3>

// === page 34 ===
Probably the most interesting, and certainly the most complex and difficult to calculate, force acting on a body moving through the atmosphere is the aerodynamic resistance to its passage, which physicists and engineers call drag.
The drag of a body is a function of the density and viscosity of the medium through which it moves, its size and shape, the velocity with which it moves, the quality of its finish, its detailed surface characteristics, and its angle of attack.

Detailed discussions of the physical mechanisms by which all these factors influence the drag of a model rocket will be presented in Chapter 3.
For the present it will be enough to write down just a few of the most fundamental facts about drag as it pertains to model rockets.
First of all, the total drag on a model rocket moving through air of density $rho$ at a velocity of magnitude $v$ is given by

$ D = 1/2 rho C_D A_r v^2 $

where $A_r$ is a reference area which is usually taken to be the cross-sectional area of the largest diameter body tube used in the rocket and $C_D$ is the drag coefficient, a dimensionless parameter which depends on the shape of the model and its angle of attack, and also (more generally) on the Reynolds number at which it is operating.

The angle of attack, usually denoted by the symbol $alpha$, is the angle between the instantaneous velocity vector of the model's C.G. with respect to the air and the orientation of the rocket's

// === page 35 ===
longitudinal axis.
The concept of angle of attack is illustrated in @fig:1-6.
As the angle of attack of a model rocket increases from zero its drag coefficient also increases, since the effective area normal --- that is, perpendicular --- to the airflow which it presents becomes larger than the reference area $A_r$ used in calculating the drag, and the effective shape of the rocket becomes more difficult for the airflow to negotiate.

The Reynolds number, named for the English physicist Osborne Reynolds (1842-1912), is usually denoted by $R_e$ and is a dimensionless aerodynamic scaling factor given by the relation

$ R_e = (rho v L)/mu $

where (again) $rho$ is the density of the air, $mu$ is the viscosity of the air, $v$ is the magnitude of the velocity vector and $L$ is the length of the rocket or other object of interest.
There is also a _kinematic viscosity_, defined as

$ nu = mu/(rho) $

so that the Reynolds number is sometimes written as

$ R_e = (v L)/nu $

The concept of viscosity will be more fully discussed and explained in Chapter 3.
For the present, the importance of equations (15) and (17) can be summed up in two statements:

(a) The flow about two geometrically similar objects is _dynamically similar_ if the Reynolds numbers for

// === page 36 ===
#figure(
 image("../../assets/figures-original/fig1-6.png"),
 caption: [Angle of attack. The direction of the rocket's longitudinal axis is deflected through the angle $alpha$ from the instantaneous velocity vector $arrow(V)$. $alpha$ is referred to as the "angle of attack". This diagram assumes that there is no horizontal wind, so that the rocket's velocity with respect to the air is the same as its velocity with respect to the ground.]
) <fig:1-6>

// === page 37 ===
the two cases are identical; and

(b) The Reynolds number expresses the ratio of _inertial_ force to _viscous_ force in any given fluid-flow situation.
The effects of _viscosity_ predominate at Reynolds numbers less than 1.0, while _inertial_ effects predominate at Reynolds numbers greater than 1.0.

Statement (a) is important to the field of aerodynamic testing in which models are used, such as wind-tunnel testing.
It means, for instance, that a quarter-scale model of an airplane placed in a wind tunnel will yield accurate information about the full-scale prototype if the tunnel airspeed is maintained at four times the flight speed of the prototype, so that the product vL is the same for the two cases (or if the tunnel is pressurized or some other fluid than air is used, so that the kinematic viscosity is decreased and a lower speed may be used).
Conversely, data taken on a model rocket placed in a wind tunnel which can only generate an airspeed of 5 meters per second may _not_ apply to that same model when it is flying 150 meters per second.

Statement (b) is important when considering the effect of varying Reynolds number on the drag coefficient.
The density of sea-level air is 1.225 x 10^{-3} gram/cm.^3, while its viscosity at room temperature (180° C) is 1.827 x 10^{-4} gram/(cm.-sec.).
The unit combination gram/(cm.-sec.) is also known as the _poise_.
In any case, this makes the value of $rho / mu$ in CGS units equal to

// === page 38 ===
6.69 sec./cm.².
With the length of a typical model rocket being about 30 centimeters, a flight velocity of 150 meters/sec.
(15,000 cm./sec.) produces a Reynolds number of about 3 x 10⁶.
An airspeed of 5 meters/second, on the other hand, gives an $R_e$ of only $1 times 10^5$.
Both numbers are considerably greater than one, of course, so that inertial forces are much greater than viscous forces in all cases involving model rockets.
Still, the two cases differ by more than an order of magnitude, so that viscous effects are _thirty times_ more important in the wind-tunnel test than in flight.
Consequently, the flow behavior observed in the wind-tunnel test may be different from that actually encountered in flight.
The drag coefficient, in particular, may be somewhat different.

Each component of a model rocket --- nosecone, body tube, fins, and so on --- contributes in some measure to the overall drag on the model, and hence to its drag coefficient.
Each contributes both _pressure drag_ due to the effect of its shape in displacing the airflow pattern about the rocket and _friction drag_ due to the _viscous shearing stress_, or "friction", of the air directly adjacent to its lateral surfaces.
The effect of the components in modifying the flow about each other also produces a small amount of additional drag, called the _interference drag_.
Changes in Reynolds number over a great enough range can change the value of the overall drag coefficient through the phenomenon of _transition_, which alters the characteristics of the airflow about the rocket.
At lower Reynolds numbers (less than $5 times 10^5$), where viscous forces are more

// === page 39 ===
important, the flow in the boundary layer directly adjacent to the model is likely to be arranged in neat, smooth, microscopically-thin layers and is thus said to be laminar.
At higher Reynolds numbers (greater than 5 x 10^6) the importance of viscosity diminishes and the boundary layer is likely to undergo transition and become turbulent; the once-smooth layers mixing and swirling down the side of the model in a rough, chaotic manner.
The friction drag of an object with a turbulent boundary layer is much higher than that of one with a laminar boundary layer, but a turbulent boundary layer follows the contour of an object's surface better than a laminar one and is less likely to separate from the surface, so it may lower the pressure drag.
Detailed discussions of precisely how much Reynolds number changes, with their associated transition phenomena, alter a model rocket's drag coefficient will be presented in Chapter 3.
The present brief discussion should be sufficient to give you a general idea of why the Reynolds number is important and how it can change the drag coefficient.
Over the range of $R_e$ usually encountered in practice, values of $C_D$ for most model rockets range from 0.35 to about 1.0, averaging 0.7 to 0.75 for sport rockets of average design and finish quality.

Chapter 3 will also present a thorough treatment of methods for calculating how a model rocket's drag coefficient increases with angle of attack.
A slightly different approach, but one which gives very nearly the same numerical results, will be used in Chapter 4 for determining the effect of dynamic oscillations

// === page 40 ===
("wobbling" of the rocket on the way up) on a model's maximum altitude.
According to this treatment, the coefficient of drag at zero angle of attack is written $C_D_0$.
A constant $k$ can then be defined such that

$ k equiv 1/2 rho A_r C_D_0 $

Then one can represent the drag as a function of angle of attack by

$ D = ( k + epsilon f(alpha)) v^2 $

where $epsilon$ is a constant and $f(alpha)$ is some function of the angle of attack that decreases to zero as the angle of attack itself goes to zero.
According to the method of analysis developed by James Barrowman, which is discussed in detail in Chapter 2, a rocket flying at a nonzero angle of attack experiences a normal force (i.e., one perpendicular to the model's centerline) whose magnitude is given by

$ N = 1/2 rho C_(N alpha) A_r v^2 $

where $C_(N alpha)$ is the normal force coefficient, whose computation by the Barrowman method is described in Chapter 2.
The component of force $N sin alpha$ is an additional contribution to the drag, while the component $N cos alpha$ is a side force tending to deflect the rocket's path by causing an acceleration component normal to the current direction of flight.
The resolution of the normal force is shown in @fig:1-7.

Now at small angles of attack (less than about 15°) $sin alpha$

// === page 41 ===
#figure(
 image("../../assets/figures-original/fig1-7.png"),
 caption: [Resolution of normal force into side force and "drag due to lift". The normal force and its components are considered to act through the center of pressure. $arrow(N)$ is perpendicular to the longitudinal axis of the rocket, $arrow(S)$ is perpendicular to the velocity vector, and $arrow(D)_1$ is parallel to the velocity vector. A case of no wind has again been assumed.]
) <fig:1-7>

// === page 42 ===
is very nearly equal to the value of $alpha$ itself in radians (one radian equals 57.3°), while $cos alpha$ is very nearly equal to 1.0.
Accordingly, one can make the small-angle approximations

#eq("21")[$ N sin alpha approx N alpha $] <eq:1-21>

#eq("22")[$ S equiv N cos alpha approx N $] <eq:1-22>

where $S$ denotes the magnitude of the side force.
Now by inspection of equations (19), (20), and (21), one might be tempted to deduce that

$ epsilon = 1/2 f C_(n alpha) A_r "and" $

$ f(alpha) = alpha^2 $

Unfortunately, things are not quite that simple.
The drag increase due to the normal force is only one of several contributions to the increase in drag produced by a nonzero angle of attack.
As explained in Chapter 3, viscous cross-flow and increased interference effects cause the increase in drag due to angle of attack to be somewhat greater than one would predict from Barrowman analysis alone.
It will, however, be found quite accurate to represent $f(alpha)$ by $alpha^2$, and this property will be used in Chapter 4 to estimate the effects of the oscillatory responses to various in-flight perturbations on altitude capability.

// === page 43 ===
In @fig:1-8 a complete vector diagram of all the forces influencing the center-of-mass motion of a model rocket in flight is presented.
The making of such a drawing, called a free-body diagram, is one of the fundamental steps in the solution of any problem in statics or dynamics since it enables one to readily visualize all the components of the forces required to write down the equations of motion.
You may find it helpful to consult @fig:1-8 of this chapter again when reading Chapter 4.
// >>> section 2.3

// <<< section 3 — generated by emit.py, edits inside will be overwritten
== Description of the Perturbing Forces <sec:1-3>

// === page 43 ===
This section will consider those forces encountered by a model rocket in flight that produce moments which rotate the

// === page 44 ===
#figure(
 image("../../assets/figures-original/fig1-8.png"),
 caption: [Forces on a model rocket in flight. Thrust, drag, weight, and side force, as well as the velocity vector, have been shown for a rocket in general flight attitude (that is, the rocket is neither flying vertically nor at zero angle of attack). Wind-free conditions have been assumed.]
) <fig:1-8>

// === page 45 ===
model about its center of gravity.
The changes in angle of attack produced by such rotations result, as we saw in @sec:1-2.3, in increased aerodynamic drag and also give rise to side forces which, if they persist for a long enough time, can seriously disturb the rocket's flight path.
The _perturbing forces_ generally arise from irregularities in the construction of the model, launching and staging effects, and local wind phenomena --- all of which must be allowed for in some degree when designing a model.
Model rockets must be designed to respond as little as possible to the perturbing forces, and to return to straight and true flight as soon as possible after the disturbance has passed.
Accordingly, the analyses of Chapters 2 and 4 will present in detail information useful in designing disturbance-resistant rockets.
// >>> section 3

// <<< section 3.1 — generated by emit.py, edits inside will be overwritten
=== Aerodynamic Disturbances <sec:1-3.1>

// === page 45 ===
Aerodynamic effects that tend to rotate a rocket vehicle about its C.G. can arise from winds, misaligned fins or other components, "fluttering" of the fins, or protrusions such as launch lugs which cause asymmetries in the vehicle's shape.
Winds may either blow continuously or arise in momentary gusts.
In Chapter 2 it will be shown that a constant wind that persists for a long period of time can produce _weathercocking_, a phenomenon in which the model tends to tip toward the direction from which the wind is coming and fly off at an angle determined by the vector sum of the wind velocity and the vertical velocity of the rocket at the time it began to experience the wind.
Weathercocking is illustrated in @fig:1-9.
A _gust_ of wind, on the other

// === page 46 ===
#figure(
 image("../../assets/figures-original/fig1-9.png"),
 caption: [Weathercocking. The rocket leaves the launcher (a) at vertical velocity $arrow(V)$ and encounters a horizontal wind of velocity $arrow(U)$. It then tends to fly off in the direction of the vector $arrow(V) + (-arrow(U))$ and "weathercocks" (b), or flies into the wind. This is because the wind acts through the center of pressure which, for any stable rocket, is behind the center of gravity.]
) <fig:1-9>

// === page 47 ===
hand, will succeed in temporarily deflecting the vehicle and will generally cause it to oscillate in rotation about its C.G., with its angle of attack passing back and forth through zero.

Fin flutter is a _periodic_ force.
That is, the fins are undergoing rapid vibrations from side to side (sometimes these vibrations are audible as a whirr, or buzz) which induce forces and moments on the model that are _sinusoidal_ (i.e., if their magnitudes were graphed versus time the resulting graphs would look like sine waves).
Flutter will be present in fins which are too thin to possess sufficient rigidity; it is evidence of poor design since it is perfectly possible (indeed, _easy_) to design fins which do not flutter at all.
If you do encounter a case of fin flutter, though, you will want your rocket to survive it so you will have a chance to replace the model's fins.
Consequently, the rocket as a whole should be designed for minimal response to any possible flutter.

Misaligned fins or other components and asymmetrical surface protrusions will cause forces and moments which are constant in direction in a rocket that is not spinning (or "rolling") about its centerline, and which are sinusoidal in nature in one that is spinning.
The _angular frequency_ of the sine functions in the latter case is equal to the roll rate of the vehicle in radians per second.
// >>> section 3.1

// <<< section 3.2 — generated by emit.py, edits inside will be overwritten
=== Mechanical Disturbances <sec:1-3.2>

// === page 47 ===
Mechanical perturbing forces and moments are distinguished from aerodynamic disturbances in that they in no way depend upon the aerodynamic coupling of the point-mass motion to

// === page 48 ===
#figure(
 image("../../assets/figures-original/fig1-10.png"),
 caption: [Examples of aerodynamic and mechanical disturbances. A horizontal wind (a) produces step forcing of constant intensity, while mismounted fins (b) cause a step disturbance of intensity proportional to the square of the airspeed. If only one fin is canted the rocket will spin, producing roll-coupled sinusoidal forcing. Torsionally vibrating fins (c) produce sinusoidal forcing of intensity proportional to the square of the airspeed. A mismounted or malfunctioning engine (d) produces step forcing proportional to the thrust level. Launch rod whip at departure (e) causes an impulse disturbance, as does staging (f). Since the lower stage has been blown to the right by the blow-through/ignition sequence, the base of the upper stage is pushed to the left. Cases (a), (b), and (c) are aerodynamic disturbances, while (d), (e), and (f) are mechanical disturbances.]
) <fig:1-10>

// === page 49 ===
// TODO figure on page 49: no caption was transcribed.
// Model described it as: Six diagrams of rocket configurations labeled a through f, showing different configuration
#conflict[Figure placeholder — page 49 needs a number and caption.]

// === page 50 ===
the model's rigid-body rotations, and that they do not originate from any aerodynamic sources at all.
Mechanical perturbations would arise even if one attempted to fly a model rocket in the hard vacuum of outer space.
Examples of mechanical disturbances are those caused by thrust misalignment due to imperfect engine mounting or nozzle abnormalities, propulsive instabilities resulting in an oscillating thrust vector, force transients arising as the vehicle leaves the launch rod or tower, and forces due to a staging ignition sequence.

Mechanical disturbances arising from launch departure effects or staging are unidirectional in nature and are of extremely short duration, while those arising from thrust misalignment or thrust vector oscillation are of relatively long duration.
Thrust oscillation effects are sinusoidal with an angular frequency determined by the rapidity of the oscillation itself.
In the case of a spinning rocket the frequency of the thrust oscillation will be superimposed upon the model's roll rate.
A constant thrust misalignment will be unidirectional in nature if the vehicle is not spinning, and sinusoidal with an angular frequency equal to the roll rate if it is.

All the perturbing effects mentioned here and in @sec:1-3.1 will be discussed in detail, modeled mathematically, and treated as input moments ("inputs" or "forcing functions") causing the model to undergo various rigid-body rotations in Chapter 2.
While reading Chapter 2 you may wish to consult @fig:1-10, in which a number of situations which will produce aerodynamic or mechanical disturbances have been illustrated.
// >>> section 3.2

// === page 51 ===
// full: true because Chapter 1 never cites these in the text; the manuscript
// just lists them, so nothing would print without it.
#bibliography("../refs-ch1.yml", style: "ieee", title: "References", full: true)
